config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resources :participants
  end

  mount Magic::Link::Engine, at: '/'

  root 'events#index'
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  belongs_to :event

  validates :email, presence: true
  validate :event_max_participants

  private

  def event_max_participants
    return unless event && event.participants.count >= event.max_participants.to_i

    errors.add(:base, 'participant limit exceeded')
  end
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  before_action :set_event
  before_action :set_participant, only: %i[show edit update destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # rubocop:disable Style/EmptyMethod
  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/1/edit
  def edit
  end
  # rubocop:enable Style/EmptyMethod

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @event, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { redirect_to @event, notice: @participant.errors.full_messages.to_sentence }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @event, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to @event, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    @participant = Participant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def participant_params
    params.require(:participant).permit(:email, :event_id)
  end
end

app/helpers/participants_helper.rb
# frozen_string_literal: true

module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= simple_form_for([@event, @participant]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.hidden_field :event_id, value: @event.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= participant.event %></td>
        <td><%= link_to 'Show', event_participant(@event) %></td>
        <td><%= link_to 'Edit', edit_event_participant_path(@event, participant) %></td>
        <td><%= link_to 'Destroy', event_participant(@event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_event_participant_path(@event) %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', event_path(@event) %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= @participant.event %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>