config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resources :participants
  end

  mount Magic::Link::Engine, at: '/'

  root 'events#index'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :participants, dependent: :destroy

  validates :event_type, presence: true
  validates :speaker, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :max_participants, presence: true, if: :workshop?

  enum event_type: %i[workshop office_hours]

  # custom validators

  validate :start_at_cannot_be_in_the_past
  validate :end_at_cannot_be_earlier_than_start_at
  validate :end_at_should_be_the_same_day_as_start_at
  validate :no_office_hour_time_overlap

  private

  # rubocop:disable Rails/FindBy
  def no_office_hour_time_overlap
    return if workshop?
    record = Event.where("name = ? AND speaker = ? AND location = ? AND ((start_at BETWEEN ? AND ?) \
                         OR (end_at BETWEEN ? AND ?))",
                         name, speaker, location, start_at, end_at, start_at, end_at).take

    errors.add(:start_at, 'timeslot already taken') if record
  end
  # rubocop:enable Rails/FindBy

  def workshop?
    event_type == 'workshop'
  end

  def start_at_cannot_be_in_the_past
    errors.add(:start_at, "can't be in the past") if start_at && start_at < Time.current
  end

  def end_at_cannot_be_earlier_than_start_at
    errors.add(:end_at, "can't be earlier than start_at") if end_at && start_at && end_at <= start_at
  end

  # no multi-day events
  def end_at_should_be_the_same_day_as_start_at
    if end_at && start_at && end_at > start_at &&
       end_at.to_date != start_at.to_date
      errors.add(:end_at, 'should be on the same day as start_at')
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  # rubocop:disable Style/SafeNavigation
  before_action only: %i[destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end
  # rubocop:enable Style/SafeNavigation

  before_action :authenticate_user!, only: %i[new update create]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :set_event_types, only: %i[new edit create update]

  # GET /events
  # GET /events.json
  def index
    if params[:term]
      search_events
    else
      @events = Event.all.includes(:participants).page params[:page]
    end
  end

  # rubocop:disable Style/EmptyMethod
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/1/edit
  def edit
  end
  # rubocop:enable Style/EmptyMethod

  # GET /events/new
  def new
    @event = Event.new
    @event_types = Event.event_types
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def search_params
    params.permit(:page, :term)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_event_types
    @event_types = Event.event_types
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:event_type, :speaker, :start_at, :end_at, :name,
                                  :location, :description, :max_participants)
  end

  def search_events
    case params[:term]
    when /off/
      event_type = Event.event_types[:office_hours]
      @events = Event.where('event_type = ?', event_type).includes(:participants).all.page params[:page]
    when /work/
      event_type = Event.event_types[:workshop]
      @events = Event.where('event_type = ?', event_type).includes(:participants).all.page params[:page]
    when /\d/
      date = Date.parse(params[:term])
      @events = Event.where('DATE(start_at) = ?', date.to_s).includes(:participants).all.page params[:page]
    else
      term = "%#{params[:term]}%"
      @events = Event.where('speaker LIKE ? OR location LIKE ?', term, term)
                     .includes(:participants).all.page params[:page]
    end
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def start_date(date)
    date.to_formatted_s(:short_ordinal)
  end

  def duration(start_at, end_at)
    ['between', start_at.to_formatted_s(:event_duration),
     'and',     end_at.to_formatted_s(:event_duration)].join(' ')
  end

  def ratio(event)
    "#{event.participants.size} / #{event.max_participants}"
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_type %>
    <%= form.select :event_type, options_for_select(@event_types.map { |t| [t[0].titleize, t[0]] }, selected: @event.event_type) %>
  </div>

  <div class="field">
    <%= form.label :speaker %>
    <%= form.text_field :speaker %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.datetime_select :start_at %>
  </div>

  <div class="field">
    <%= form.label :end_at %>
    <%= form.datetime_select :end_at %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :max_participants %>
    <%= form.number_field :max_participants %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_participants.html.erb
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event.participants.each do |participant| %>
    <tr>
      <td><%= participant.email %></td>
      <td><%= link_to 'Destroy', [@event, participant], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(events_path, method: :get) do %>
<%= text_field_tag :term %>
<%= submit_tag 'Search' %>
<% end %>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Event type</th>
      <th>Speaker</th>
      <th>Date</th>
      <th>Duration</th>
      <th>Location</th>
      <th>Description</th>
      <th>Participants</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name.titleize, event  %></td>
        <td><%= event.event_type.titleize %></td>
        <td><%= event.speaker.titleize %></td>
        <td><%= start_date(event.start_at) %></td>
        <td><%= duration(event.start_at, event.end_at) %></td>
        <td><%= event.location.titleize %></td>
        <td><%= event.description %></td>
        <td><%= ratio(event) %></td>
        <td><%= link_to('Edit', edit_event_path(event)) if current_user.try(:admin?) %></td>
        <td><%= link_to('Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }) if current_user.try(:admin?) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @events %>
<%= link_to('New Event', new_event_path) if user_signed_in? %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name.titleize %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @event.event_type.titleize %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @event.speaker.titleize %>
</p>

<p>
  <strong>Date:</strong>
  <%= start_date(@event.start_at) %>
</p>

<p>
  <strong>Duration:</strong>
  <%= duration(@event.start_at, @event.end_at) %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location.titleize %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<h2>Participants <%= ratio(@event) %></h2>

<%= render partial: 'participants' %>

<%= link_to 'Edit', edit_event_path(@event) if user_signed_in? %>
<%= link_to 'Back', events_path %>
<%= link_to 'Add participant', new_event_participant_path(@event) %>